### PR TITLE
Cope with change in Travis that now requires sudo for some steps.

### PR DESCRIPTION
**Pull request by martinhbramwell**
https://forums.meteor.com/t/travis-build-failing-before-starting/2141

### CODE REVIEW

**Comment by arunoda** [comment]
Nice. Could you remove all spacejam related code set.

**Comment by arunoda** [comment]
And add a note on the README about these recent changes. So, someone which has the issue knows, what to do. May be link to the meteor forum link as well.

**Comment by martinhbramwell** [comment]
I did as you asked.  How will Git react?  Must I close this PR and create another? Or will it pull the two edits I just did on line since this PR?

**Comment by arunoda** [comment]
Yeah! GitHub will merge those commits. We can use this PR.

**Comment by martinhbramwell** [comment]
Great!  I leave closing the PR up to you.

**Comment by arunoda** [comment]
Okay. I merged it already :)

**Comment by mitar** [comment]
Yes, this was required since few days. I forgot to report it. :-)

**Pull request merged**
